/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.api.production.jsonc --include-runtime=false --strict-vars=false --env-interface=WorkerBindings server/worker-configuration.d.ts` (hash: fc76c280b807d16927a7a80f37906ce3)
interface __BaseEnv_WorkerBindings {
	FILES: R2Bucket;
	DB: D1Database;
	APP_ORIGIN: string;
	API_ORIGIN: string;
	CLOUDFLARE_ACCOUNT_ID: string;
	OPENROUTER_MODEL: string;
	REALTIME_APP_ID: string;
	AUTH_SECRET: string;
	API_BASE_URL: string;
	CHAT_ROOMS: DurableObjectNamespace<import("./worker").ChatRoom>;
	MATCHMAKER: DurableObjectNamespace<import("./worker").Matchmaker>;
	BILLING: DurableObjectNamespace<import("./worker").BillingCoordinator>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "ChatRoom" | "Matchmaker" | "BillingCoordinator";
	}
	interface Env extends __BaseEnv_WorkerBindings {}
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN" | "API_ORIGIN" | "CLOUDFLARE_ACCOUNT_ID" | "OPENROUTER_MODEL" | "REALTIME_APP_ID" | "AUTH_SECRET" | "API_BASE_URL">> {}
}
